<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYgmuvdd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYgmuvdd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYgmuvdd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYgmuvdd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYgmuvdd\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ygmuvdd',
    'container.build_id' => 'b5e6d1f3',
    'container.build_time' => 1622730054,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYgmuvdd');
