<?php

namespace ContainerYgmuvdd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCrudControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CrudController' shared autowired service.
     *
     * @return \App\Controller\CrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CrudController.php';

        $container->services['App\\Controller\\CrudController'] = $instance = new \App\Controller\CrudController(($container->services['router'] ?? $container->getRouterService()));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\CrudController', $container));

        return $instance;
    }
}
